[package]
name = "chessosity-rs-cozy"
# (Major update version).(Evaluation / search function update version).(Bugfix / patch version)
# TODO: Update version every commit
version = "3.5.4"
edition = "2021"

[dependencies]
cozy-chess = "0.3.4"