[package]
name = "chessosity-rs-cozy"
# (Major update version).(Evaluation function update version).(Bugfix / patch version)
# TODO: Update version every commit
version = "3.4.0"
edition = "2021"

[dependencies]
cozy-chess = "0.3.4"